version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: sribrown_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: sribrown_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      # Use the Docker service name "db" as the host for MySQL connection
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sribrown_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - db

volumes:
  db_data:
